extern "C" void fs_mkfs(FILE * fp, struct file_system * F);
extern "C" int fs_open(FILE * fp, struct file_system * F, const char *filename, const char *flag);
extern "C" char * fs_read(FILE * fp, struct file_system * F, int file_d, int size);
extern "C" void fs_write(FILE * fp, struct file_system * F, int file_d, const char * w_string);
extern "C" void fs_seek(FILE * fp, struct file_system * F, int fd, int offset);
extern "C" void fs_close(FILE * fp, struct file_system * F, int fd);
extern "C" void fs_mkdir(FILE * fp, struct file_system * F, const char *dirname);
extern "C" void fs_rmdir(FILE * fp, struct file_system * F, const char *dirname);
extern "C" void fs_cd(struct file_system * F, FILE * fp, const char *dirname);
extern "C" void fs_ls(FILE * fp, struct file_system * F);
extern "C" void fs_cat();
extern "C" void fs_tree();
extern "C" void fs_import();
extern "C" void fs_export();
